language: node_js
node_js:
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
script:
  - npm run check:src
  - npm run build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
after_success: npm run test:cov